### ISSUE TITLE
Training workflow does not work on Visual Genome

### ISSUE THREAD

**Issue by YerongLi2** [Vision-CAIR/LTVRR#7]
`    python tools/train_net_step_rel.py --dataset vg8k --cfg configs/vg8k/e2e_relcnn_VGG16_8_epochs_vg8k_y_loss_only_hubness100k.yaml --nw 8 --use_tfboard --seed 3`

    INFO train_net_step_rel.py: 663: Save ckpt on exception ...
    INFO train_net_step_rel.py: 150: save model: Outputs/e2e_relcnn_VGG16_8_epochs_vg8k_y_loss_only_hubness100k/vg8k/Apr02-00-17-05_bock_step_with_prd_cls
    _v3/ckpt/model_step0.pth
    INFO train_net_step_rel.py: 665: Save ckpt done.
    Traceback (most recent call last):
      File "tools/train_net_step_rel.py", line 604, in main
        net_outputs = maskRCNN(**input_data)
      File "/home/wentaoy2/anaconda3/envs/vr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/wentaoy2/LTVRR/lib/nn/parallel/data_parallel.py", line 108, in forward
        outputs = [self.module(*inputs[0], **kwargs[0])]
      File "/home/wentaoy2/anaconda3/envs/vr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/wentaoy2/LTVRR/lib/modeling/model_builder_rel.py", line 513, in forward
        return self._forward(data, im_info, dataset_name, roidb, use_gt_labels, include_feat, **rpn_kwargs)
      File "/home/wentaoy2/LTVRR/lib/modeling/model_builder_rel.py", line 553, in _forward
        assert len(roidb) == 1
  AssertionError

**Comment by aniket-agarwal1999** [comment]
Hi,
I am not sure why this could be occurring. I tried to reproduce this by a completely new setup but did not get this error. Can I once know if you have properly compiled the Detectron submodule along with all the other instructions on the README?
